ALTER TABLE pacjent MODIFY
PARTITION BY LIST(rodzaj_swiadczenia)(
    PARTITION pacjentpremium VALUES ('Premium'),
    PARTITION pacjentpremiumplus VALUES ('Premium+'),
    PARTITION pacjentpodstawowe VALUES ('Podstawowe')
);

ALTER TABLE wizyta MODIFY
PARTITION BY RANGE (rozpoczecie)
INTERVAL
(
    NUMTOYMINTERVAL(1, 'MONTH')
)
(
    PARTITION P_DEC2018 VALUES LESS THAN (TO_DATE('01/01/2019','DD/MM/YYYY'))
);

ALTER TABLE WIZYTA MODIFY
PARTITION BY RANGE(ROZPOCZECIE)
INTERVAL(NUMTOYMINTERVAL(1,'MONTH'))
SUBPARTITION BY LIST(CZY_PRYWATNA)
SUBPARTITION TEMPLATE
(
    SUBPARTITION PT VALUES ('T'),
    SUBPARTITION PF VALUES ('F')
)
(
    PARTITION P1 VALUES LESS THAN(TO_DATE('01-01-2019','DD-MM-YYYY')),
    PARTITION P2 VALUES LESS THAN(TO_DATE('01-02-2019','DD-MM-YYYY')),
    PARTITION P3 VALUES LESS THAN(TO_DATE('01-03-2019','DD-MM-YYYY'))
);

ALTER TABLE PACJENT MODIFY
PARTITION BY LIST(STATUS_SWIADCZENIA)
SUBPARTITION BY LIST(RODZAJ_SWIADCZENIA)
SUBPARTITION TEMPLATE
(
    SUBPARTITION podstawowe VALUES ('Podstawowe'),
    SUBPARTITION premiumplus VALUES ('Premium+'),
    SUBPARTITION premium VALUES ('Premium')
)
(
    PARTITION aktywne VALUES ('Aktywne'),
    PARTITION zakonczone VALUES ('Zakończone'),
    PARTITION zawieszone VALUES ('Zawieszone')
);